export const START_TVSHOWS_REQUEST_FROM_API = "START_TVSHOWS_REQUEST_FROM_API";
export const END_TVSHOWS_REQUEST_FROM_API = "END_TVSHOWS_REQUEST_FROM_API";
export const SEARCH_TVSHOWS = "SEARCH_TVSHOWS";
export const ADD_TVSHOWS_TO_MY_LIST = "ADD_TVSHOWS_TO_MY_LIST";
export const GET_TVSHOWS_FROM_MY_LIST = "GET_TVSHOWS_FROM_MY_LIST";
export const CHANGE_TAB = "CHANGE_TAB";